function [edits, button, dispTexts, texts] = UIFrame(myuiPositions)
%build all my uicontrols handle, myuiPositions contain all the position 
% and size to create the uicontrols.
%edits：struct{sourceMacEdit; destMacEdit; dataEdit}
%button: the process buttons
%dispTexts: struct{LengthDispText; crcDispText; frameDispText}
%texts: row vector, contain the handle of the static texts for identing different parts.

    f = figure(3);
    
    %sourceMacEdit 
    %destMacEdit
    %dataEdit
    edits.sourceMacEdit = uicontrol(f, ...
        'Style', 'edit', ...
        'Position', myuiPositions.sourceMacEdit);
        
    edits.destMacEdit = uicontrol(f, ...
        'Style', 'edit', ...
        'Position', myuiPositions.destMacEdit);
            
    edits.dataEdit = uicontrol(f, ...
        'Style', 'edit', ...
        'Max', 5, ...
        'Min', 0, ...
        'Position', myuiPositions.dataEdit);
    
    %frameText
    %crcText
    %lengthText
    %dataText
    %sourceMacText
    %destMacText
    %LengthDispText
    %crcDispText
    %frameDispText
    texts = zeros(6, 1);
    
    texts(1) = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'Frame:',...
        'Position', myuiPositions.frameText...
    );
    texts(2) = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'FCS:',...
        'Position', myuiPositions.crcText...
    );
    texts(3) = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'Length',...
        'Position', myuiPositions.lengthText...
    );
    texts(4) = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'Data:',...
        'Position', myuiPositions.dataText...
    );
    texts(5) = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'SourceMac:',...
        'Position', myuiPositions.sourceMacText...
    );
    texts(6) = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'DestMac:',...
        'Position', myuiPositions.destMacText...
    );
    dispTexts.LengthDispText = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'Unknown',...
        'Position', myuiPositions.LengthDispText...
    );
    dispTexts.crcDispText = uicontrol(f, ...
        'Style', 'text', ...
        'String', 'Unknown',...
        'Position', myuiPositions.crcDispText...
    );
    dispTexts.frameDispText = uicontrol(f, ...
        'Style', 'edit', ...
        'String', 'Unknown',...
        'Max', 5,...
        'Min', 0,...
        'Position', myuiPositions.frameDispText...
    );
    
    button = uicontrol(f, ...
        'Style', 'pushbutton', ...
        'String', 'Process',...
        'Position', myuiPositions.button...
    );
    
    
end
