function [edits, texts, buttons] = UIFrame(myuiPositions)
    f = figure(3);
    
    %sourceMacEdit 
    %destMacEdit
    %dataEdit
    edits = zeros(3, 1);
    edits(1) = uicontrol(f, ...
        'Style', 'edit', ...
        'Position', myuiPositions.sourceMacEdit);
        
    edits(2) = uicontrol(f, ...
        'Style', 'edit', ...
        'Position', myuiPositions.destMacEdit);
            
    edits(3) = uicontrol(f, ...
        'Style', 'edit', ...
        'Position', myuiPositions.dataEdit);
    
    %frameText
    %crcText
    %lengthText
    %dataText
    %sourceMacText
    %destMacText
    %LengthDispText
    %crcDispText
    %frameDispText
    texts = zeros(9, 1);
    
    texts(1) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.frameText...
    );
    texts(2) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.crcText...
    );
    texts(3) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.lengthText...
    );
    texts(4) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.dataText...
    );
    texts(5) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.sourceMacText...
    );
    texts(6) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.destMacText...
    );
    texts(7) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.LengthDispText...
    );
    texts(8) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.crcDispText...
    );
    texts(9) = uicontrol(f, ...
        'Style', 'text', ...
        'String', '封装结果',...
        'Position', myuiPositions.frameDispText...
    );
    
    
    %button
    buttons = zeros(1, 1);
    
    buttons(1) = uicontrol(f, ...
        'Style', 'pushbutton', ...
        'String', '开始处理',...
        'Position', myuiPositions.button...
    );
    
    
end
